# Generated by Django 3.2.8 on 2021-10-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domaininfo',
            options={'verbose_name': 'domain_api_list', 'verbose_name_plural': 'domain_api_list'},
        ),
        migrations.RemoveField(
            model_name='appinfo',
            name='update_by',
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='update_by',
        ),
        migrations.AddField(
            model_name='appinfo',
            name='AppFilter',
            field=models.CharField(db_column='update_by', default='daiyi', max_length=32, null=True, verbose_name='AppFilter'),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='AppFilter',
            field=models.CharField(db_column='update_by', default='daiyi', max_length=32, null=True, verbose_name='AppFilter'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='create_by',
            field=models.CharField(db_column='create_by', default='daiyi', max_length=32, verbose_name='create_by'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='create_time',
            field=models.DateTimeField(db_column='create_time', null=True),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='delete_mark',
            field=models.SmallIntegerField(db_column='delete_mark', default=0, help_text='delete_mark'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='domain_id_belonged',
            field=models.CharField(db_column='domain_id_belonged', help_text='domain_id_belonged', max_length=32),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_column='update_time', null=True),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='create_by',
            field=models.CharField(db_column='create_by', default='daiyi', max_length=32, verbose_name='create_by'),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='create_time',
            field=models.DateTimeField(db_column='create_time', null=True),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='delete_mark',
            field=models.SmallIntegerField(db_column='delete_mark', default=0, help_text='delete_mark'),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='domain_id',
            field=models.AutoField(db_column='domain_id', help_text='domain_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='domian_admin',
            field=models.CharField(db_column='domian_admin', help_text='domian_admin', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='domian_detail',
            field=models.CharField(db_column='domian_detail', help_text='domian_detail', max_length=3332, null=True),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='domian_name',
            field=models.CharField(db_column='domian_name', help_text='domian_name', max_length=32),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_column='update_time', null=True),
        ),
    ]
